---
- name: keys add iff they are in files/pubkeys
  authorized_key:
    user: root
    # Pipe to concatenate SSH keys
    # See https://stackoverflow.com/a/38879787
    key: "{{ lookup('pipe', 'cat {{ key_dir }}/*pub') }}"
    exclusive: "{{ keys_exclusive }}"
  become: true
- name: set timezone
  timezone:
    name: "{{ timezone }}"
- name: generate locales
  locale_gen:
    name: "{{ locale }}"
    state: present
  # Module does not seem to work on CentOS 7
  # Module uses /etc/locale.gen, which CentOS 7 might not
  when: 
    (ansible_distribution != "CentOS") or
    (ansible_distribution_major_version != "7")
- import_tasks: packages.yml
