---
- name: set timezone
  timezone:
    name: "{{ timezone }}"
- name: generate locales
  locale_gen:
    name: "{{ locale }}"
    state: present
  # Module does not seem to work on CentOS 7
  # Module uses /etc/locale.gen, which CentOS 7 might not
  when: 
    (ansible_distribution != "CentOS") or
    (ansible_distribution_major_version != "7")
- import_tasks: packages.yml
